server:
  port: 9003

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/won_auth
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true