server:
  port: 9003

spring:
  application:
    name: user-service

  data:
    jpa:
      repositories:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/won_user
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

passport:
  key: ${SECRETE_KEY}
  algorithm: HmacSHA256

grpc:
  server:
    port: 9803