server:
  port: 9004

spring:
  application:
    name: auth-service
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  expiration:
    access: 86400000
    refresh: 604800000
  key: ${SECRETE_KEY}

passport:
  key: ${SECRETE_KEY}
  algorithm: HmacSHA256

grpc:
  client:
    local-grpc-server:
      address: 'static://localhost:9803'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext